### PR TITLE
Update fini

### PR DESCRIPTION
**Pull request by ghost**
Added subreddit and LinkedIn Group link

### CODE REVIEW

**Comment by Hjdskes** [comment]
It's BunsenLabs. Do we really need a subreddit and even more so, a LinkedIn?

**Comment by Sector11** [comment]
I was going to say the same, you beat me to it.

**Comment by ghost** [comment]
The LinkedIn was just for a few interested souls, but the subreddit was
been well received. I just thought it would help with those who had
questions/news regarding the project and for finding help in transitioning
from current #! systems

**Comment by ghost** [comment]
*has been.
I just feel like a stronger online presence will lead to more interest in
the project, which might help this project progress smoother.

**Comment by yellowire** [comment]
Well hey, could you guys use a web developer? I've been lurking the #! forums for a couple years, and am totally pumped for this Bunsen Labs build. I don't feel qualified to help much with configs & install scripts and stuff, but I'd be happy to lend a hand toward building a Bunsen Labs site.

**Comment by Hjdskes** [comment]
A website is something we will work on after getting an initial version out. You can open a topic for this on the forums or create a separate issue (tho there is no good repository to make such an issue on, so forums preferred) to discuss this.

As for the web-presence, I agree a subreddit is a good thing to have - I just don't understand why a LinkedIn page is needed.

**Comment by ghost** [comment]
I can always delete the LinkedIn group. I was just trying to include what I thought some people would prefer to use.

**Comment by ghost** [comment]
I will go ahead and adjust the pull request

**Comment by fu-sen** [comment]
It's not "official community". It would be the reason that has been rejected.
Information of the official community it will be obtained from the Web.
It is by the current output, BunsenLabs users should be able to confirm.

**Pull request closed without merging**
